# Generated by Django 5.0.2 on 2024-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('option_type', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(max_length=255, null=True)),
                ('expiry', models.CharField(max_length=255, null=True)),
                ('strike', models.CharField(max_length=255, null=True)),
                ('qty', models.IntegerField()),
                ('underlying_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sl_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('underlying_sl_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('underlying_target_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
